version: '3.8'

services:
  blacksheep:
    build: ./blacksheep
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./blacksheep:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
