version: '3.8'

services:
  fastapi:
    build: ./fastapi
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./fastapi:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - ENVIRONMENT=dev

  blacksheep:
    build: ./blacksheep
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./blacksheep:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev

  flask:
    build: ./flask
    command: flask run --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./flask:/usr/src/app
    ports:
      - 8003:8000
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
  
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/usr/src/app
    ports:
      - 8004:8000
    environment:
      - DEBUG=1

  nestjs:
    build: ./nestjs
    command: npm run start:dev
    volumes:
      - ./nestjs:/usr/src/app
    ports:
      - 8005:8000
    environment:
      - ENVIRONMENT=development
